/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arac_alis_satis;

import java.sql.Statement;

//database için gerekli kütüphaneler


/**
 *
 * @author user
 */
public class ana_ekran extends javax.swing.JFrame {

    /**
     * Creates new form ana_ekran
     */
    public ana_ekran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbll_alis_sati = new javax.swing.JLabel();
        lbl_resim = new javax.swing.JLabel();
        lbl_islem_sec = new javax.swing.JLabel();
        cmb_islemler = new javax.swing.JComboBox<>();
        btn_sec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(204, 204, 204));

        lbll_alis_sati.setBackground(new java.awt.Color(255, 255, 255));
        lbll_alis_sati.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbll_alis_sati.setForeground(new java.awt.Color(51, 51, 51));
        lbll_alis_sati.setText("ARAÇ ALIŞ SATIŞ PROGRAMI ");
        lbll_alis_sati.setToolTipText("");

        lbl_resim.setBackground(new java.awt.Color(255, 255, 255));
        lbl_resim.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\arac_alis_satis\\if_app_type_rent_a_car_512px_GREY_287483 (1).png")); // NOI18N

        lbl_islem_sec.setBackground(new java.awt.Color(255, 255, 255));
        lbl_islem_sec.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_islem_sec.setForeground(new java.awt.Color(102, 102, 102));
        lbl_islem_sec.setText("İşlem seçiniz : ");

        cmb_islemler.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        cmb_islemler.setForeground(new java.awt.Color(51, 51, 51));
        cmb_islemler.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kayıt Ekle", "Kayıt Sil", "Kayıt Güncelle", "Filtrele" }));

        btn_sec.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btn_sec.setForeground(new java.awt.Color(51, 51, 51));
        btn_sec.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\arac_alis_satis\\if_check-tick-mark-correct-choose_3209370.png")); // NOI18N
        btn_sec.setText("SEÇ");
        btn_sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_secActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_resim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lbl_islem_sec)
                                .addGap(18, 18, 18)
                                .addComponent(cmb_islemler, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbll_alis_sati)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(btn_sec)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_resim, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lbll_alis_sati, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_islem_sec, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_islemler, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_sec, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_secActionPerformed
       if(cmb_islemler.getSelectedItem().toString()=="Kayıt Ekle"){
           kayit_ekle ke=new kayit_ekle();
           ke.setTitle("KAYIT EKLEME");
           ke.setLocationRelativeTo(null);
           ke.setVisible(true);
       }
       else if(cmb_islemler.getSelectedItem().toString()=="Kayıt Sil"){
           kayit_sil ks=new kayit_sil();
           ks.setTitle("KAYIT SİLME");
           ks.setLocationRelativeTo(null);
           ks.setVisible(true);
       }
       else if(cmb_islemler.getSelectedItem().toString()=="Kayıt Güncelle"){
           guncelle g=new guncelle();
           g.setTitle("KAYIT GÜNCELLEME");
           g.setLocationRelativeTo(null);
           g.setVisible(true);
       }
       else if(cmb_islemler.getSelectedItem().toString()=="Filtrele"){
           filtrele f=new filtrele();
           f.setTitle("FİLTRELEME");
           f.setLocationRelativeTo(null);
           f.setVisible(true);
       }
        
    }//GEN-LAST:event_btn_secActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ana_ekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ana_ekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ana_ekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ana_ekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ana_ekran().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sec;
    private javax.swing.JComboBox<String> cmb_islemler;
    private javax.swing.JLabel lbl_islem_sec;
    private javax.swing.JLabel lbl_resim;
    private javax.swing.JLabel lbll_alis_sati;
    // End of variables declaration//GEN-END:variables
}
