/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arac_alis_satis;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class kayit_ekle extends javax.swing.JFrame {

    /**
     * Creates new form kayit_ekle
     */
    public kayit_ekle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tablo_sec = new javax.swing.JLabel();
        cmb_tablolar = new javax.swing.JComboBox<>();
        lbl_kayit_ekle = new javax.swing.JLabel();
        lbl_resim = new javax.swing.JLabel();
        btn_ekle = new javax.swing.JButton();
        btn_veri_tabani_goruntule = new javax.swing.JButton();
        lbl_1 = new javax.swing.JLabel();
        lbl_2 = new javax.swing.JLabel();
        lbl_3 = new javax.swing.JLabel();
        lbl_4 = new javax.swing.JLabel();
        lbl_5 = new javax.swing.JLabel();
        lbl_6 = new javax.swing.JLabel();
        lbl_7 = new javax.swing.JLabel();
        txt_1 = new javax.swing.JTextField();
        txt_2 = new javax.swing.JTextField();
        txt_3 = new javax.swing.JTextField();
        txt_4 = new javax.swing.JTextField();
        txt_5 = new javax.swing.JTextField();
        txt_6 = new javax.swing.JTextField();
        txt_7 = new javax.swing.JTextField();

        lbl_tablo_sec.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_tablo_sec.setForeground(new java.awt.Color(51, 51, 51));
        lbl_tablo_sec.setText("Tablo seç : ");

        cmb_tablolar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        cmb_tablolar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tbl_ilan", "tbl_araba", "tbl_renk", "tbl_sehir", "tbl_vites_turu", "tbl_yakit_turu" }));
        cmb_tablolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tablolarActionPerformed(evt);
            }
        });

        lbl_kayit_ekle.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_kayit_ekle.setForeground(new java.awt.Color(51, 51, 51));
        lbl_kayit_ekle.setText("KAYIT EKLEME");

        lbl_resim.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\arac_alis_satis\\if_floppy-disk_531889.png")); // NOI18N

        btn_ekle.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btn_ekle.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\arac_alis_satis\\if_flat-style-circle-add_1312548.png")); // NOI18N
        btn_ekle.setText("EKLE");
        btn_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekleActionPerformed(evt);
            }
        });

        btn_veri_tabani_goruntule.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btn_veri_tabani_goruntule.setForeground(new java.awt.Color(51, 51, 51));
        btn_veri_tabani_goruntule.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\arac_alis_satis\\if_document-open_118911.png")); // NOI18N
        btn_veri_tabani_goruntule.setText("VERİ TABANI GÖRÜNTÜLE");
        btn_veri_tabani_goruntule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_veri_tabani_goruntuleActionPerformed(evt);
            }
        });

        lbl_1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_1.setForeground(new java.awt.Color(51, 51, 51));
        lbl_1.setText("ilan_id       : ");

        lbl_2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_2.setForeground(new java.awt.Color(51, 51, 51));
        lbl_2.setText("ilan_adı      : ");

        lbl_3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_3.setForeground(new java.awt.Color(51, 51, 51));
        lbl_3.setText("ilan_fiyat    : ");

        lbl_4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_4.setForeground(new java.awt.Color(51, 51, 51));
        lbl_4.setText("ilan_km       : ");

        lbl_5.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_5.setForeground(new java.awt.Color(51, 51, 51));
        lbl_5.setText("ilan_tarih(yy/aa/gg) : ");

        lbl_6.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_6.setForeground(new java.awt.Color(51, 51, 51));
        lbl_6.setText("ilan_araba_id : ");

        lbl_7.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_7.setForeground(new java.awt.Color(51, 51, 51));
        lbl_7.setText("ilan_sehir_id : ");

        txt_1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        txt_2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        txt_3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        txt_4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        txt_5.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        txt_6.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txt_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_6ActionPerformed(evt);
            }
        });

        txt_7.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_resim)
                .addGap(18, 18, 18)
                .addComponent(lbl_kayit_ekle)
                .addGap(292, 292, 292))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btn_veri_tabani_goruntule)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lbl_4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lbl_5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_6, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_7, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_6, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_7, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(332, 332, 332))
                                    .addComponent(txt_5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(lbl_tablo_sec)
                                .addGap(18, 18, 18)
                                .addComponent(cmb_tablolar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 124, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lbl_kayit_ekle))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_resim, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_tablolar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tablo_sec))
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_veri_tabani_goruntule))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_tablolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tablolarActionPerformed
        txt_1.grabFocus();
        if(cmb_tablolar.getSelectedItem().toString()=="tbl_ilan"){
                lbl_1.setText("ilan_id       : ");
                lbl_2.setText("ilan_adı      : ");
                lbl_3.setVisible(true);
                lbl_3.setText("ilan_fiyat    : ");
                lbl_4.setVisible(true);
                lbl_4.setText("ilan_km       : ");
                lbl_5.setVisible(true);
                lbl_5.setText("ilan_tarih(yy/aa/gg) : ");
                lbl_6.setVisible(true);
                lbl_6.setText("ilan_araba_id : ");
                lbl_7.setVisible(true);
                lbl_7.setText("ilan_sehir_id : ");
                
                txt_1.setText("");
                txt_1.setVisible(true);
                txt_2.setText("");
                txt_2.setVisible(true);
                txt_3.setText("");
                txt_3.setVisible(true);
                txt_4.setText("");
                txt_4.setVisible(true);
                txt_5.setText("");
                txt_5.setVisible(true);
                txt_6.setText("");
                txt_6.setVisible(true);
                txt_7.setText("");
                txt_7.setVisible(true);
                
        }
        else if(cmb_tablolar.getSelectedItem().toString()=="tbl_araba"){
            lbl_1.setText("araba_id            : ");
            lbl_2.setText("araba_marka         : ");
            lbl_3.setVisible(true);
            lbl_3.setText("araba_model         : ");
            lbl_4.setVisible(true);
            lbl_4.setText("araba_vites_turu_id : ");
            lbl_5.setVisible(true);
            lbl_5.setText("araba_yakit_turu_id : ");
            lbl_6.setVisible(true);
            lbl_6.setText("araba_renk_id       : ");
            lbl_7.setVisible(false);
            
            txt_1.setText("");
            txt_1.setVisible(true);
            txt_2.setText("");
            txt_2.setVisible(true);
            txt_3.setText("");
            txt_3.setVisible(true);
            txt_4.setText("");
            txt_4.setVisible(true);
            txt_5.setText("");
            txt_5.setVisible(true);
            txt_6.setText("");
            txt_6.setVisible(true);
            txt_7.setText("");
            txt_7.setVisible(false);
        }
        else if(cmb_tablolar.getSelectedItem().toString()=="tbl_renk"){
            lbl_1.setText("renk_id : ");
            lbl_2.setText("renk    : ");
            lbl_3.setVisible(false);
            lbl_4.setVisible(false);
            lbl_5.setVisible(false);
            lbl_6.setVisible(false);
            lbl_7.setVisible(false);
            
            txt_1.setText("");
            txt_1.setVisible(true);
            txt_2.setText("");
            txt_2.setVisible(true);
            txt_3.setText("");
            txt_3.setVisible(false);
            txt_4.setText("");
            txt_4.setVisible(false);
            txt_5.setText("");
            txt_5.setVisible(false);
            txt_6.setText("");
            txt_6.setVisible(false);
            txt_7.setText("");
            txt_7.setVisible(false);
        }
        else if(cmb_tablolar.getSelectedItem().toString()=="tbl_sehir"){
            lbl_1.setText("sehir_id : ");
            lbl_2.setText("sehir    : ");
            lbl_3.setVisible(false);
            lbl_4.setVisible(false);
            lbl_5.setVisible(false);
            lbl_6.setVisible(false);
            lbl_7.setVisible(false);
            
            txt_1.setText("");
            txt_1.setVisible(true);
            txt_2.setText("");
            txt_2.setVisible(true);
            txt_3.setText("");
            txt_3.setVisible(false);
            txt_4.setText("");
            txt_4.setVisible(false);
            txt_5.setText("");
            txt_5.setVisible(false);
            txt_6.setText("");
            txt_6.setVisible(false);
            txt_7.setText("");
            txt_7.setVisible(false);
        }
        else if(cmb_tablolar.getSelectedItem().toString()=="tbl_vites_turu"){
            lbl_1.setText("vites_turu_id : ");
            lbl_2.setText("vites_turu    : ");
            lbl_3.setVisible(false);
            lbl_4.setVisible(false);
            lbl_5.setVisible(false);
            lbl_6.setVisible(false);
            lbl_7.setVisible(false);
            
            txt_1.setText("");
            txt_1.setVisible(true);
            txt_2.setText("");
            txt_2.setVisible(true);
            txt_3.setText("");
            txt_3.setVisible(false);
            txt_4.setText("");
            txt_4.setVisible(false);
            txt_5.setText("");
            txt_5.setVisible(false);
            txt_6.setText("");
            txt_6.setVisible(false);
            txt_7.setText("");
            txt_7.setVisible(false);
        }
        else if(cmb_tablolar.getSelectedItem().toString()=="tbl_yakit_turu"){
            lbl_1.setText("yakit_turu_id : ");
            lbl_2.setText("yakit_turu    : ");
            lbl_3.setVisible(false);
            lbl_4.setVisible(false);
            lbl_5.setVisible(false);
            lbl_6.setVisible(false);
            lbl_7.setVisible(false);
            
            txt_1.setText("");
            txt_1.setVisible(true);
            txt_2.setText("");
            txt_2.setVisible(true);
            txt_3.setText("");
            txt_3.setVisible(false);
            txt_4.setText("");
            txt_4.setVisible(false);
            txt_5.setText("");
            txt_5.setVisible(false);
            txt_6.setText("");
            txt_6.setVisible(false);
            txt_7.setText("");
            txt_7.setVisible(false);
        }
    }//GEN-LAST:event_cmb_tablolarActionPerformed

    private void btn_veri_tabani_goruntuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_veri_tabani_goruntuleActionPerformed
        veri_tabani_goster vt=new veri_tabani_goster();
        vt.setTitle("VERİ TABANI");
        vt.setLocationRelativeTo(null);
        vt.setVisible(true);
         
    }//GEN-LAST:event_btn_veri_tabani_goruntuleActionPerformed

    private void btn_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekleActionPerformed
        
        
        
        String query1;
        try{
        //query seçilen tabloya göre oluştu
        Class.forName("com.mysql.jdbc.Connection");
        Connection c=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/aaaa","root","170201097");
        Statement stm=(Statement)c.createStatement();
        int executeUpdate;
        if(cmb_tablolar.getSelectedItem().toString()=="tbl_ilan"){
           query1="insert into tbl_ilan(ilan_id,ilan_adi,ilan_fiyat,ilan_km,ilan_tarih,ilan_araba_id,ilan_sehir_id) values("
                       +"'"+Integer.parseInt(txt_1.getText())+"'"
                       + ","
                       +"'"+txt_2.getText()+"'"
                       + ","
                       +"'"+Float.parseFloat(txt_3.getText())+"'"
                       + ","
                       +"'"+Integer.parseInt(txt_4.getText())+"'"
                       + ","
                       +"'"+txt_5.getText()+"'"
                       + ","
                       +"'"+Integer.parseInt(txt_6.getText())+"'"
                       + ","
                       +"'"+Integer.parseInt(txt_7.getText())+"')";
            executeUpdate=stm.executeUpdate(query1);
           
        }
        else if(cmb_tablolar.getSelectedItem().toString()=="tbl_araba"){
            query1="insert into tbl_araba(araba_id,araba_marka,araba_model,araba_vites_turu_id,araba_yakit_turu_id,araba_renk_id) values("
                    +"'"+Integer.parseInt(txt_1.getText())+"'"
                    + ","
                    +"'"+txt_2.getText()+"'"
                    + ","
                    +"'"+txt_3.getText()+"'"
                    + ","
                    +"'"+Integer.parseInt(txt_4.getText())+"'"
                    + ","
                    +"'"+Integer.parseInt(txt_5.getText())+"'"
                    + ","
                    +"'"+Integer.parseInt(txt_6.getText())+"')";
            executeUpdate=stm.executeUpdate(query1);
        }
        else if(cmb_tablolar.getSelectedItem().toString()=="tbl_renk"){
            query1="insert into tbl_renk(renk_id,renk) values("
                    +"'"+Integer.parseInt(txt_1.getText())+"'"
                    + ","
                    +"'"+txt_2.getText()+"')";
                    
            executeUpdate=stm.executeUpdate(query1);
        }
        else if(cmb_tablolar.getSelectedItem().toString()=="tbl_sehir"){
            query1="insert into tbl_sehir(sehir_id,sehir) values("
                    +"'"+Integer.parseInt(txt_1.getText())+"'"
                    + ","
                    +"'"+txt_2.getText()+"')";
                    
            executeUpdate=stm.executeUpdate(query1);
        }
        else if(cmb_tablolar.getSelectedItem().toString()=="tbl_vites_turu"){
            query1="insert into tbl_vites_turu(vites_tur_id,vites_turu) values("
                    +"'"+Integer.parseInt(txt_1.getText())+"'"
                    + ","
                    +"'"+txt_2.getText()+"')";
                    
            executeUpdate=stm.executeUpdate(query1);
        }
        else if(cmb_tablolar.getSelectedItem().toString()=="tbl_yakit_turu"){
            query1="insert into tbl_yakit_turu(yakit_turu_id,yakit_turu) values("
                    +"'"+Integer.parseInt(txt_1.getText())+"'"
                    + ","
                    +"'"+txt_2.getText()+"')";
                    
            executeUpdate=stm.executeUpdate(query1);
        }
        JOptionPane.showMessageDialog(null,"Kayıt ekleme işlemi başarılı.");
        c.close();
       } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null,"Kayıt ekleme işlemi başarısız.");
       } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Kayıt ekleme işlemi başarısız.");
       }
        
                
        
    }//GEN-LAST:event_btn_ekleActionPerformed

    private void txt_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kayit_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kayit_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kayit_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kayit_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kayit_ekle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ekle;
    private javax.swing.JButton btn_veri_tabani_goruntule;
    private javax.swing.JComboBox<String> cmb_tablolar;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_3;
    private javax.swing.JLabel lbl_4;
    private javax.swing.JLabel lbl_5;
    private javax.swing.JLabel lbl_6;
    private javax.swing.JLabel lbl_7;
    private javax.swing.JLabel lbl_kayit_ekle;
    private javax.swing.JLabel lbl_resim;
    private javax.swing.JLabel lbl_tablo_sec;
    private javax.swing.JTextField txt_1;
    private javax.swing.JTextField txt_2;
    private javax.swing.JTextField txt_3;
    private javax.swing.JTextField txt_4;
    private javax.swing.JTextField txt_5;
    private javax.swing.JTextField txt_6;
    private javax.swing.JTextField txt_7;
    // End of variables declaration//GEN-END:variables
}
