/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arac_alis_satis;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author user
 */
public class kayit_sil extends javax.swing.JFrame {

    /**
     * Creates new form kayit_sil
     */
    public kayit_sil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_resim = new javax.swing.JLabel();
        lbl_kayit_sil = new javax.swing.JLabel();
        btn_sil = new javax.swing.JButton();
        lbl_tablo_sec = new javax.swing.JLabel();
        cmb_tablolar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tablolar = new javax.swing.JTable();

        lbl_resim.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\arac_alis_satis\\if_Delete_files_folder_data_remove_1886811.png")); // NOI18N

        lbl_kayit_sil.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_kayit_sil.setForeground(new java.awt.Color(51, 51, 51));
        lbl_kayit_sil.setText("KAYIT SİLME");

        btn_sil.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btn_sil.setForeground(new java.awt.Color(51, 51, 51));
        btn_sil.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\arac_alis_satis\\if_Streamline-70_185090.png")); // NOI18N
        btn_sil.setText("SİL");
        btn_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silActionPerformed(evt);
            }
        });

        lbl_tablo_sec.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_tablo_sec.setForeground(new java.awt.Color(51, 51, 51));
        lbl_tablo_sec.setText("Tablo seç : ");

        cmb_tablolar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        cmb_tablolar.setForeground(new java.awt.Color(51, 51, 51));
        cmb_tablolar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tbl_ilan", "tbl_araba", "tbl_renk", "tbl_sehir", "tbl_vites_turu", "tbl_yakit_turu" }));
        cmb_tablolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tablolarActionPerformed(evt);
            }
        });

        tbl_tablolar.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jScrollPane1.setViewportView(tbl_tablolar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_resim)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_kayit_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_tablo_sec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_tablolar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                        .addComponent(btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_resim, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lbl_kayit_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tablo_sec)
                    .addComponent(cmb_tablolar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_sil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silActionPerformed
        
        //Jtabledan silmek için
        DefaultTableModel model=(DefaultTableModel)tbl_tablolar.getModel();
        int row=tbl_tablolar.getSelectedRow();
        
        String selected=tbl_tablolar.getModel().getValueAt(row, 0).toString();
        
        if(row>=0){
            model.removeRow(row);
            
        try{
        //query seçilen tabloya göre oluştu
        Class.forName("com.mysql.jdbc.Connection");
        Connection c=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/aaaa","root","170201097");
        Statement stm=(Statement)c.createStatement();
        String query;
        int executeUpdate;
        
        if(cmb_tablolar.getSelectedItem().toString()=="tbl_ilan"){
           query="delete from tbl_ilan where ilan_id='"
                   +selected+"'";
           executeUpdate=stm.executeUpdate(query);
           
        }
        else if(cmb_tablolar.getSelectedItem().toString()=="tbl_araba"){
            query="delete from tbl_araba where araba_id='"
                   +selected+"'";
           executeUpdate=stm.executeUpdate(query);
        }
        else if(cmb_tablolar.getSelectedItem().toString()=="tbl_renk"){
            query="delete from tbl_renk where renk_id='"
                   +selected+"'";
           executeUpdate=stm.executeUpdate(query);
        }
        else if(cmb_tablolar.getSelectedItem().toString()=="tbl_sehir"){
            query="delete from tbl_sehir where sehir_id='"
                   +selected+"'";
           executeUpdate=stm.executeUpdate(query);
        
        }
        else if(cmb_tablolar.getSelectedItem().toString()=="tbl_vites_turu"){
            query="delete from tbl_vites_turu where vites_turu_id='"
                   +selected+"'";
           executeUpdate=stm.executeUpdate(query);
        
        }
        else if(cmb_tablolar.getSelectedItem().toString()=="tbl_yakit_turu"){
            query="delete from tbl_yakit_turu where yakit_turu_id='"
                   +selected+"'";
           executeUpdate=stm.executeUpdate(query);
        }
        JOptionPane.showMessageDialog(null,"Kayıt silme işlemi başarılı.");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Kayıt silme işlemi başarısız.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Kayıt silme işlemi başarısız.");
        }
        }
    }//GEN-LAST:event_btn_silActionPerformed

    private void cmb_tablolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tablolarActionPerformed
       try{
        //query seçilen tabloya göre oluştu
        Class.forName("com.mysql.jdbc.Connection");
        Connection c=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/aaaa","root","170201097");
        Statement stm=(Statement)c.createStatement(); 
        
        
        if(cmb_tablolar.getSelectedItem().toString()=="tbl_ilan"){
           try(ResultSet rs =stm.executeQuery("Select * from tbl_ilan")){
            int colCount=rs.getMetaData().getColumnCount();
            DefaultTableModel tm=new DefaultTableModel();
            for(int i=1;i<=colCount;i++)
                tm.addColumn(rs.getMetaData().getColumnName(i));
            while(rs.next()){
                Object[] row=new Object[colCount];
                for(int j=1;j<=colCount;j++)
                    row[j-1]=rs.getObject(j);
                tm.addRow(row);
            }
            tbl_tablolar.setModel(tm);
        }
           
        }
        else if(cmb_tablolar.getSelectedItem().toString()=="tbl_araba"){
            try(ResultSet rs =stm.executeQuery("Select * from tbl_araba")){
            int colCount=rs.getMetaData().getColumnCount();
            DefaultTableModel tm=new DefaultTableModel();
            for(int i=1;i<=colCount;i++)
                tm.addColumn(rs.getMetaData().getColumnName(i));
            while(rs.next()){
                Object[] row=new Object[colCount];
                for(int j=1;j<=colCount;j++)
                    row[j-1]=rs.getObject(j);
                tm.addRow(row);
            }
            tbl_tablolar.setModel(tm);
        }
        }
        else if(cmb_tablolar.getSelectedItem().toString()=="tbl_renk"){
            try(ResultSet rs =stm.executeQuery("Select * from tbl_renk")){
            int colCount=rs.getMetaData().getColumnCount();
            DefaultTableModel tm=new DefaultTableModel();
            for(int i=1;i<=colCount;i++)
                tm.addColumn(rs.getMetaData().getColumnName(i));
            while(rs.next()){
                Object[] row=new Object[colCount];
                for(int j=1;j<=colCount;j++)
                    row[j-1]=rs.getObject(j);
                tm.addRow(row);
            }
            tbl_tablolar.setModel(tm);
        }
        }
        else if(cmb_tablolar.getSelectedItem().toString()=="tbl_sehir"){
            try(ResultSet rs =stm.executeQuery("Select * from tbl_sehir")){
            int colCount=rs.getMetaData().getColumnCount();
            DefaultTableModel tm=new DefaultTableModel();
            for(int i=1;i<=colCount;i++)
                tm.addColumn(rs.getMetaData().getColumnName(i));
            while(rs.next()){
                Object[] row=new Object[colCount];
                for(int j=1;j<=colCount;j++)
                    row[j-1]=rs.getObject(j);
                tm.addRow(row);
            }
            tbl_tablolar.setModel(tm);
        }
        }
        else if(cmb_tablolar.getSelectedItem().toString()=="tbl_vites_turu"){
            try(ResultSet rs =stm.executeQuery("Select * from tbl_vites_turu")){
            int colCount=rs.getMetaData().getColumnCount();
            DefaultTableModel tm=new DefaultTableModel();
            for(int i=1;i<=colCount;i++)
                tm.addColumn(rs.getMetaData().getColumnName(i));
            while(rs.next()){
                Object[] row=new Object[colCount];
                for(int j=1;j<=colCount;j++)
                    row[j-1]=rs.getObject(j);
                tm.addRow(row);
            }
            tbl_tablolar.setModel(tm);
        }
        }
        else if(cmb_tablolar.getSelectedItem().toString()=="tbl_yakit_turu"){
            try(ResultSet rs =stm.executeQuery("Select * from tbl_yakit_turu")){
            int colCount=rs.getMetaData().getColumnCount();
            DefaultTableModel tm=new DefaultTableModel();
            for(int i=1;i<=colCount;i++)
                tm.addColumn(rs.getMetaData().getColumnName(i));
            while(rs.next()){
                Object[] row=new Object[colCount];
                for(int j=1;j<=colCount;j++)
                    row[j-1]=rs.getObject(j);
                tm.addRow(row);
            }
            tbl_tablolar.setModel(tm);
        }
        }
        //Diğer seçeneklerde yeniden bağlantı kurabilmek için 
        c.close();
        } catch (ClassNotFoundException ex ) {
            Logger.getLogger(veri_tabani_goster.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(veri_tabani_goster.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmb_tablolarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kayit_sil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kayit_sil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kayit_sil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kayit_sil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
                new kayit_sil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sil;
    private javax.swing.JComboBox<String> cmb_tablolar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_kayit_sil;
    private javax.swing.JLabel lbl_resim;
    private javax.swing.JLabel lbl_tablo_sec;
    private javax.swing.JTable tbl_tablolar;
    // End of variables declaration//GEN-END:variables
}
